
# Syntax highlighting
markdown:            redcarpet
highlighter:         pygments

# Permalinks
permalink:           /:title
relative_permalinks: true

# Setup
timezone:            America/New_York # eg. Asia/Kathmandu
locale:              en_us # eg. en_us
name:				         Open Make
title:               Open Make
tagline:             'Personal Ideation of Maker Based Education'
description:         'Personal Ideation of Maker Based Education'
url:                 openmake.org
rss:                 openmake.org
baseurl:             '/'
baseurl_posts_img:   '/assets/images/posts/'
baseurl_featured_img: '/assets/images/hero/'
baseurl_featured_thumbnail: '/assets/images/thumbnail/'
baseurl_javascripts: '/assets/javascripts/'
icon:                /assets/images/osi_symbol.png # /assets/img/icon.png [best 300px X 300px]
disqus:              openmake # get it on https://disqus.com/admin/

author:
  name:           	 Hampton Paulk
  url:            	 hamptonpaulk.com
  facebook:          x
  twitter:           hamptonpaulk
  google_plus:       x
  linkedin:          x
  dribbble:          x
  pinterest:         x
  kiva:              x

fb_admins:           your facebook profile id
fb_appid:            your facebook app id

# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:             	 9001

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
